spring:
  profiles:
    active:
    - dog
    - EN
    - dev
  output:
    ansi:
      enabled: ALWAYS
daniel:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlURL

---
spring:
  profile: prod
daniel:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdURL